apiVersion: apps/v1
kind: Deployment
metadata:
  name: yutio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yutio
  template:
    metadata:
      labels:
        app: yutio
    spec:
      containers:
      - image: okteto.dev/yutio:latest
        name: yutio
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d69c60fd-a460-4cb6-a5f2-53e7039f9cf5"
        - name: Vless_Path
          value: "/udhfgfd"
        - name: Vmess_UUID
          value: "d69c60fd-a460-4cb6-a5f2-53e7039f9cf5"
        - name: Vmess_Path
          value: "/sfdsttr"
        - name: Share_Path
          value: "/v2link"
